// This file was auto-generated by Fern from our API Definition.

export interface GetV1PricesResponse {
    items?: GetV1PricesResponse.Items.Item[] | undefined;
}

export namespace GetV1PricesResponse {
    export type Items = Items.Item[];

    export namespace Items {
        export interface Item {
            /** Asset group symbol, e.g. USDT, USDC, ETH. */
            group?: string | undefined;
            /** USD price of one whole unit of the asset group. */
            priceUsd?: string | undefined;
            /** Unix timestamp (ms) when this price was last refreshed. */
            updatedAtUnixMs?: number | undefined;
        }
    }
}
