// This file was auto-generated by Fern from our API Definition.

import type * as SuwardSDK from "../../../index.js";

export interface GetV1AssetGroupsResponse {
    items?: SuwardSDK.CryptopayAssetGroupResponse[] | undefined;
}
