// This file was auto-generated by Fern from our API Definition.

import type * as SuwardSDK from "../../../../index.js";

/**
 * @example
 *     {
 *         staticWalletId: "staticWalletId"
 *     }
 */
export interface CryptopayUpdateStaticWalletRequest {
    /** Static wallet ID */
    staticWalletId: string;
    allowedAssets?: SuwardSDK.CryptopayAssetId[];
    metadata?: Record<string, unknown>;
    webhookUrl?: string;
}
