// This file was auto-generated by Fern from our API Definition.

import type * as SuwardSDK from "../../../../index.js";

/**
 * @example
 *     {}
 */
export interface CryptopayCreateStaticWalletRequest {
    allowedAssets?: SuwardSDK.CryptopayAssetId[];
    externalId?: string;
    isTest?: boolean;
    metadata?: Record<string, unknown>;
    webhookUrl?: string;
}
