// This file was auto-generated by Fern from our API Definition.

import type * as SuwardSDK from "../../../../index.js";

/**
 * @example
 *     {
 *         staticWalletId: "staticWalletId"
 *     }
 */
export interface CryptopaySimulateStaticDepositRequest {
    /** Static wallet ID */
    staticWalletId: string;
    amount?: string;
    asset?: SuwardSDK.CryptopayAssetId;
    status?: CryptopaySimulateStaticDepositRequest.Status;
    transferIndex?: string;
    txHash?: string;
}

export namespace CryptopaySimulateStaticDepositRequest {
    export const Status = {
        Detected: "detected",
        Accepted: "accepted",
        Confirmed: "confirmed",
        Invalidated: "invalidated",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
}
