// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         staticWalletId: "staticWalletId"
 *     }
 */
export interface DeleteV1StaticWalletsStaticWalletIdRequest {
    /** Static wallet ID */
    staticWalletId: string;
}
