// This file was auto-generated by Fern from our API Definition.

import type * as SuwardSDK from "../../../../index.js";

/**
 * @example
 *     {
 *         staticWalletId: "staticWalletId"
 *     }
 */
export interface GetV1StaticWalletsStaticWalletIdDepositsRequest {
    /** Static wallet ID */
    staticWalletId: string;
    /** Sort order (asc/desc) */
    order?: SuwardSDK.GetV1StaticWalletsStaticWalletIdDepositsRequestOrder;
    /** Limit (default 20, max 100) */
    limit?: number;
    /** Last ID for pagination */
    lastId?: string;
}
