// This file was auto-generated by Fern from our API Definition.

import type * as SuwardSDK from "../../../../index.js";

/**
 * @example
 *     {}
 */
export interface GetV1StaticWalletsRequest {
    /** Sort order (asc/desc) */
    order?: SuwardSDK.GetV1StaticWalletsRequestOrder;
    /** Limit (default 20, max 100) */
    limit?: number;
    /** Last ID for pagination */
    lastId?: string;
}
