// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         staticWalletId: "staticWalletId",
 *         depositId: "depositId"
 *     }
 */
export interface GetV1StaticWalletsStaticWalletIdDepositsDepositIdRequest {
    /** Static wallet ID */
    staticWalletId: string;
    /** Deposit ID */
    depositId: string;
}
