// This file was auto-generated by Fern from our API Definition.

export const GetV1StaticWalletsRequestOrder = {
    Asc: "asc",
    Desc: "desc",
} as const;
export type GetV1StaticWalletsRequestOrder =
    (typeof GetV1StaticWalletsRequestOrder)[keyof typeof GetV1StaticWalletsRequestOrder];
