// This file was auto-generated by Fern from our API Definition.

export const GetV1StaticWalletsStaticWalletIdDepositsRequestOrder = {
    Asc: "asc",
    Desc: "desc",
} as const;
export type GetV1StaticWalletsStaticWalletIdDepositsRequestOrder =
    (typeof GetV1StaticWalletsStaticWalletIdDepositsRequestOrder)[keyof typeof GetV1StaticWalletsStaticWalletIdDepositsRequestOrder];
