// This file was auto-generated by Fern from our API Definition.

import type * as SuwardSDK from "../index.js";

export interface CryptopayQuotePaymentResponse {
    asset?: SuwardSDK.CryptopayAssetId | undefined;
    /** Gross amount, integer string in the asset's smallest unit. */
    amount?: string | undefined;
    /** Platform fee: 0.4% of the amount, minimum $1 equivalent. Integer string in the asset's smallest unit. */
    fee?: string | undefined;
    /** Estimated on-chain (gas) cost, deducted from the received amount. Integer string in the asset's smallest unit. */
    networkFee?: string | undefined;
    /** Amount the merchant receives after all fees. Integer string in the asset's smallest unit. */
    netAmount?: string | undefined;
    /** Amount the customer pays: base plus any customer-paid fees. Integer string in the asset's smallest unit. */
    gross?: string | undefined;
    /** USD price used for this quote, decimal string. Not locked — the binding price is captured when the payment is created. */
    quotedPrice?: string | undefined;
}
