// This file was auto-generated by Fern from our API Definition.

import type * as SuwardSDK from "../index.js";

export interface CryptopayListStaticWalletsResponse {
    hasMore?: boolean | undefined;
    items?: SuwardSDK.CryptopayStaticWalletResponse[] | undefined;
    lastId?: string | undefined;
}
