// This file was auto-generated by Fern from our API Definition.

export interface CryptopayRedirectConfigDto {
    data?: string | undefined;
    params?: CryptopayRedirectConfigDto.Params.Item[] | undefined;
    url?: string | undefined;
}

export namespace CryptopayRedirectConfigDto {
    export type Params = Params.Item[];

    export namespace Params {
        export const Item = {
            Id: "id",
            ExternalId: "externalId",
        } as const;
        export type Item = (typeof Item)[keyof typeof Item];
    }
}
