// This file was auto-generated by Fern from our API Definition.

import type * as SuwardSDK from "../index.js";

export interface CryptopayStaticWalletResponse {
    address?: string | undefined;
    allowedAssets?: SuwardSDK.CryptopayAssetId[] | undefined;
    createdAt?: number | undefined;
    externalId?: string | undefined;
    id?: string | undefined;
    isTest?: boolean | undefined;
    metadata?: Record<string, unknown> | undefined;
    projectId?: string | undefined;
    updatedAt?: number | undefined;
    webhookUrl?: string | undefined;
}
