// This file was auto-generated by Fern from our API Definition.

import type * as SuwardSDK from "../index.js";

export interface CryptopayWithdrawalConfigResponse {
    /** Flat per-withdrawal fee in USD (decimal string). */
    withdrawalFeeUsd?: string | undefined;
    /** Asset/network pairs available for withdrawal. */
    assets?: SuwardSDK.CryptopayAssetResponse[] | undefined;
}
