// This file was auto-generated by Fern from our API Definition.

export interface CryptopayAssetGroupResponse {
    /** Numeric asset-group id. */
    id?: number | undefined;
    /** Group symbol, e.g. USDT, USDC, ETH. */
    name?: string | undefined;
}
