// This file was auto-generated by Fern from our API Definition.

import type * as SuwardSDK from "../index.js";

export interface CryptopayPublicPaymentResponse {
    activatedAt?: number | undefined;
    activationFlowSeconds?: number | undefined;
    address?: string | undefined;
    amount?: string | undefined;
    amountReceived?: string | undefined;
    asset?: SuwardSDK.CryptopayAssetId | undefined;
    createdAt?: number | undefined;
    expiresAt?: number | undefined;
    id?: string | undefined;
    paymentWindowSeconds?: number | undefined;
    redirect?: SuwardSDK.CryptopayPublicRedirect | undefined;
    status?: SuwardSDK.CryptopayPaymentStatusEnum | undefined;
    subStatus?: SuwardSDK.CryptopayPaymentSubStatusEnum | undefined;
    underpaymentTolerance?: string | undefined;
    updatedAt?: number | undefined;
}
