// This file was auto-generated by Fern from our API Definition.

/** Asset id-string (see GET /v1/assets), e.g. USDT_ETHEREUM. */
export const CryptopayAssetId = {
    UsdtEthereum: "USDT_ETHEREUM",
    UsdtArbitrum: "USDT_ARBITRUM",
    UsdtOptimism: "USDT_OPTIMISM",
    UsdtBase: "USDT_BASE",
    UsdtBsc: "USDT_BSC",
    UsdtPlasma: "USDT_PLASMA",
    UsdtPolygon: "USDT_POLYGON",
    UsdcEthereum: "USDC_ETHEREUM",
    UsdcArbitrum: "USDC_ARBITRUM",
    UsdCeArbitrum: "USDCE_ARBITRUM",
    UsdcOptimism: "USDC_OPTIMISM",
    UsdcBase: "USDC_BASE",
    UsdcBsc: "USDC_BSC",
    UsdcPlasma: "USDC_PLASMA",
    UsdcPolygon: "USDC_POLYGON",
    EthEthereum: "ETH_ETHEREUM",
    EthArbitrum: "ETH_ARBITRUM",
    EthOptimism: "ETH_OPTIMISM",
    EthBase: "ETH_BASE",
    XplPlasma: "XPL_PLASMA",
    BnbBsc: "BNB_BSC",
    PolPolygon: "POL_POLYGON",
    TestcoinEthereum: "TESTCOIN_ETHEREUM",
    TestcoinOptimism: "TESTCOIN_OPTIMISM",
    TestcoinPlasma: "TESTCOIN_PLASMA",
    TeststablecoinEthereum: "TESTSTABLECOIN_ETHEREUM",
    TeststablecoinOptimism: "TESTSTABLECOIN_OPTIMISM",
    TeststablecoinPlasma: "TESTSTABLECOIN_PLASMA",
} as const;
export type CryptopayAssetId = (typeof CryptopayAssetId)[keyof typeof CryptopayAssetId];
