// This file was auto-generated by Fern from our API Definition.

/** Who bears a fee: absorbed = deducted from the merchant's proceeds (default); onTop = added on top of the customer charge. */
export const CryptopayFeePayer = {
    Absorbed: "absorbed",
    OnTop: "onTop",
} as const;
export type CryptopayFeePayer = (typeof CryptopayFeePayer)[keyof typeof CryptopayFeePayer];
