// This file was auto-generated by Fern from our API Definition.

import type * as SuwardSDK from "../index.js";

export interface CryptopayListStaticWalletsResponse {
    /** True when more static wallets exist beyond this page. To fetch the next page, pass the last item's id as the lastId query parameter. */
    hasMore: boolean;
    /** Page of static wallets, ordered per the request's order parameter. */
    items: SuwardSDK.CryptopayStaticWalletResponse[];
}
