// This file was auto-generated by Fern from our API Definition.

/** Terminal states: success (finalized), failed (terminal, no valid payment). Non-final: pending (awaiting funds), accepted (safe confirmations reached, credited — non-final until finalized). */
export const CryptopayPaymentStatusEnum = {
    Pending: "pending",
    Accepted: "accepted",
    Success: "success",
    Failed: "failed",
} as const;
export type CryptopayPaymentStatusEnum = (typeof CryptopayPaymentStatusEnum)[keyof typeof CryptopayPaymentStatusEnum];
