// This file was auto-generated by Fern from our API Definition.

export interface CryptopayTransactionResponse {
    acceptedAt?: number | undefined;
    amount?: string | undefined;
    detectedAt?: number | undefined;
    txHash?: string | undefined;
}
