// This file was auto-generated by Fern from our API Definition.

/** Who bears a fee: merchant = deducted from the merchant's proceeds (default); customer = added on top of the customer charge. */
export const CryptopayFeePayer = {
    Merchant: "merchant",
    Customer: "customer",
} as const;
export type CryptopayFeePayer = (typeof CryptopayFeePayer)[keyof typeof CryptopayFeePayer];
