// This file was auto-generated by Fern from our API Definition.

import type * as SuwardSDK from "../index.js";

export interface CryptopayListStaticDepositsResponse {
    hasMore?: boolean | undefined;
    items?: SuwardSDK.CryptopayStaticDepositResponse[] | undefined;
    lastId?: string | undefined;
}
