// This file was auto-generated by Fern from our API Definition.

import type * as SuwardSDK from "../index.js";

export interface CryptopayStaticDepositResponse {
    acceptedAt?: number | undefined;
    address?: string | undefined;
    amount?: string | undefined;
    asset?: SuwardSDK.CryptopayAssetId | undefined;
    confirmedAt?: number | undefined;
    createdAt?: number | undefined;
    detectedAt?: number | undefined;
    /** ExternalID is the static wallet's externalId, denormalized onto the deposit. */
    externalId?: string | undefined;
    fee?: string | undefined;
    id?: string | undefined;
    invalidatedAt?: number | undefined;
    netAmount?: string | undefined;
    networkFee?: string | undefined;
    projectId?: string | undefined;
    staticWalletId?: string | undefined;
    status?: CryptopayStaticDepositResponse.Status | undefined;
    transferIndex?: string | undefined;
    txHash?: string | undefined;
    updatedAt?: number | undefined;
}

export namespace CryptopayStaticDepositResponse {
    export const Status = {
        Detected: "detected",
        Accepted: "accepted",
        Confirmed: "confirmed",
        Ignored: "ignored",
        Invalidated: "invalidated",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
}
