// This file was auto-generated by Fern from our API Definition.

import type * as SuwardSDK from "../index.js";

export interface CryptopayListPaymentsResponse {
    hasMore?: boolean | undefined;
    items?: SuwardSDK.CryptopayPaymentResponse[] | undefined;
    lastId?: string | undefined;
}
