// This file was auto-generated by Fern from our API Definition.

/** AML screening depth for a payment. extended (default) runs paid providers and carries the $0.45 minimum service fee; basic runs only free checks and waives the minimum fee (0.4% only). */
export const CryptopayComplianceLevel = {
    Basic: "basic",
    Extended: "extended",
} as const;
export type CryptopayComplianceLevel = (typeof CryptopayComplianceLevel)[keyof typeof CryptopayComplianceLevel];
