// This file was auto-generated by Fern from our API Definition.

export interface CryptopayRedirectConfigDto {
    /** Opaque string passed through unchanged as the "data" query parameter on the return URL. Use it to carry your own session/order token. */
    data?: string | undefined;
    /** Which payment identifiers to append to the return URL as query parameters. Allowed values: "id" (the Suward payment id) and "externalId" (your identifier). */
    params?: CryptopayRedirectConfigDto.Params.Item[] | undefined;
    /** Base "return to store" URL the customer is sent back to after paying. */
    url: string;
}

export namespace CryptopayRedirectConfigDto {
    export type Params = Params.Item[];

    export namespace Params {
        export const Item = {
            Id: "id",
            ExternalId: "externalId",
        } as const;
        export type Item = (typeof Item)[keyof typeof Item];
    }
}
