// This file was auto-generated by Fern from our API Definition.

import type * as SuwardSDK from "../index.js";

export interface CryptopayAssetResponse {
    id?: SuwardSDK.CryptopayAssetId | undefined;
    /** Internal blockchain ID (corresponds to GET /v1/blockchains[].id). */
    blockchainId?: number | undefined;
    /** ERC20 contract address; null for native coins (ETH, BNB, POL, XPL). */
    contractAddress?: (string | null) | undefined;
    /** Number of decimal places: smallest-unit amounts are whole tokens * 10^decimals. */
    decimals?: number | undefined;
    /** Asset group, e.g. USDT, USDC, ETH. */
    group?: string | undefined;
    /** Human-readable asset name. */
    name?: string | undefined;
}
