// This file was auto-generated by Fern from our API Definition.

/** overpaid / underpaid: more or less than the requested amount was received. partiallyPaid: payment expired with a partial payment that never reached acceptance. complianceHold: held (under pending) for compliance review. complianceRejected: rejected by compliance (terminal, under failed). */
export const CryptopayPaymentSubStatusEnum = {
    Created: "created",
    Activated: "activated",
    AwaitingPayment: "awaitingPayment",
    Confirming: "confirming",
    Completed: "completed",
    Overpaid: "overpaid",
    Underpaid: "underpaid",
    Expired: "expired",
    Cancelled: "cancelled",
    PartiallyPaid: "partiallyPaid",
    ComplianceHold: "complianceHold",
    ComplianceRejected: "complianceRejected",
} as const;
export type CryptopayPaymentSubStatusEnum =
    (typeof CryptopayPaymentSubStatusEnum)[keyof typeof CryptopayPaymentSubStatusEnum];
