// This file was auto-generated by Fern from our API Definition.

export const CryptopayPaymentStatusEnum = {
    Pending: "pending",
    Accepted: "accepted",
    Success: "success",
    Failed: "failed",
} as const;
export type CryptopayPaymentStatusEnum = (typeof CryptopayPaymentStatusEnum)[keyof typeof CryptopayPaymentStatusEnum];
