// This file was auto-generated by Fern from our API Definition.

export interface CryptopayTransactionResponse {
    /** Unix-milliseconds timestamp when the transfer reached the accepted (safe) confirmation tier. Null before acceptance. */
    acceptedAt?: number | undefined;
    /** On-chain transfer amount, an integer string in the asset's smallest unit (see CreatePaymentRequest.amount). */
    amount?: string | undefined;
    /** Unix-milliseconds timestamp when the transfer was first seen on-chain. */
    detectedAt?: number | undefined;
    /** On-chain transaction hash of the transfer. */
    txHash?: string | undefined;
}
