// This file was auto-generated by Fern from our API Definition.

import type * as SuwardSDK from "../index.js";

/**
 * Webhook body for a static-wallet deposit transition. Signed over the raw body with the project's Ed25519 key; verify with project.webhookPublicKey. `createdAt` is the signed, trusted timestamp; `staticDeposit` is the full deposit resource.
 */
export interface WebhookStaticDepositEvent {
    type: WebhookStaticDepositEvent.Type;
    eventId: string;
    /** Event creation time, unix milliseconds. */
    createdAt: number;
    staticDeposit: SuwardSDK.CryptopayStaticDepositResponse;
}

export namespace WebhookStaticDepositEvent {
    export const Type = {
        StaticDepositAccepted: "static_deposit.accepted",
        StaticDepositSuccess: "static_deposit.success",
    } as const;
    export type Type = (typeof Type)[keyof typeof Type];
}
