// This file was auto-generated by Fern from our API Definition.

import type * as SuwardSDK from "../index.js";

/**
 * Webhook body for a payment lifecycle transition. Signed over the raw body with the project's Ed25519 key; verify with project.webhookPublicKey. `createdAt` is the signed, trusted timestamp; `payment` is the full payment resource (the same shape as the merchant GET /v1/payments/{paymentId} view). Obtain `webhookPublicKey` from your project settings in the Suward dashboard.
 */
export interface WebhookPaymentEvent {
    type: WebhookPaymentEvent.Type;
    eventId: string;
    /** Event creation time, unix milliseconds. */
    createdAt: number;
    payment: SuwardSDK.CryptopayPaymentResponse;
}

export namespace WebhookPaymentEvent {
    export const Type = {
        PaymentAccepted: "payment.accepted",
        PaymentSuccess: "payment.success",
        PaymentFailed: "payment.failed",
    } as const;
    export type Type = (typeof Type)[keyof typeof Type];
}
