// This file was auto-generated by Fern from our API Definition.

/**
 * Webhook body for a payment lifecycle transition. Signed over the raw body with the project's Ed25519 key; verify with project.webhookPublicKey. `createdAt` is the signed, trusted timestamp.
 */
export interface WebhookPaymentEvent {
    type: WebhookPaymentEvent.Type;
    eventId: string;
    /** Event creation time, unix milliseconds. */
    createdAt: number;
    paymentId: string;
    projectId: string;
    externalId?: string | undefined;
    status: string;
    subStatus: string;
    amount: string;
    amountReceived: string;
    amountConfirmed: string;
    assetId?: number | undefined;
}

export namespace WebhookPaymentEvent {
    export const Type = {
        PaymentAccepted: "payment.accepted",
        PaymentSuccess: "payment.success",
        PaymentFailed: "payment.failed",
    } as const;
    export type Type = (typeof Type)[keyof typeof Type];
}
