// This file was auto-generated by Fern from our API Definition.

import type * as SuwardSDK from "../../../../index.js";

/**
 * @example
 *     {}
 */
export interface CryptopayCreatePaymentRequest {
    activationFlowSeconds?: number;
    amount?: string;
    asset?: SuwardSDK.CryptopayAssetId;
    externalId?: string;
    isTest?: boolean;
    metadata?: Record<string, unknown>;
    paymentWindowSeconds?: number;
    redirectConfig?: SuwardSDK.CryptopayRedirectConfigDto;
    underpaymentTolerance?: string;
    webhookUrl?: string;
}
