// This file was auto-generated by Fern from our API Definition.

import type * as SuwardSDK from "../../../../index.js";

/**
 * @example
 *     {}
 */
export interface CryptopayCreatePaymentRequest {
    activationFlowSeconds?: number;
    /** Merchant base amount, integer string in the asset's smallest unit. When a fee payer is customer the customer is charged more than this (gross); when merchant (default) the fee is deducted from the merchant's proceeds. */
    amount?: string;
    asset?: SuwardSDK.CryptopayAssetId;
    /** Who bears the network (gas) fee. Default merchant. */
    networkFeePayer?: SuwardSDK.CryptopayFeePayer;
    /** Who bears the platform (service) fee. Default merchant. */
    serviceFeePayer?: SuwardSDK.CryptopayFeePayer;
    externalId?: string;
    metadata?: Record<string, unknown>;
    paymentWindowSeconds?: number;
    redirectConfig?: SuwardSDK.CryptopayRedirectConfigDto;
    underpaymentTolerance?: string;
    webhookUrl?: string;
}
