// This file was auto-generated by Fern from our API Definition.

import type * as SuwardSDK from "../../../../index.js";

/**
 * @example
 *     {
 *         asset: "USDT_ETHEREUM",
 *         amount: "amount"
 *     }
 */
export interface CryptopayQuotePaymentRequest {
    /** Asset identifier (see GET /v1/assets for the live list). */
    asset: SuwardSDK.CryptopayAssetId;
    /** Merchant base amount, integer string in the asset's smallest unit. Example: "5000000" = 5 USDT. The response returns the derived gross (what the customer pays) and netAmount (what the merchant receives). */
    amount: string;
    /** Who bears the network (gas) fee. Default merchant. */
    networkFeePayer?: SuwardSDK.CryptopayFeePayer;
    /** Who bears the platform (service) fee. Default merchant. */
    serviceFeePayer?: SuwardSDK.CryptopayFeePayer;
    /** AML screening depth to quote: basic (free, no minimum fee) or extended ($0.45 minimum fee). Omit to inherit the project/org default (extended). */
    complianceLevel?: SuwardSDK.CryptopayComplianceLevel;
}
