// This file was auto-generated by Fern from our API Definition.

import type * as SuwardSDK from "../../../../index.js";

/**
 * @example
 *     {
 *         paymentId: "paymentId"
 *     }
 */
export interface CryptopaySimulatePaymentRequest {
    /** Payment ID */
    paymentId: string;
    amount?: string;
    subStatus?: SuwardSDK.CryptopayPaymentSubStatusEnum;
}
