// This file was auto-generated by Fern from our API Definition.

import type * as SuwardSDK from "../../../../index.js";

/**
 * @example
 *     {
 *         asset: "USDT_ETHEREUM",
 *         amount: "amount"
 *     }
 */
export interface CryptopayQuotePaymentRequest {
    /** Asset identifier (see GET /v1/assets for the live list). */
    asset: SuwardSDK.CryptopayAssetId;
    /** Gross amount, integer string in the asset's smallest unit. Example: "5000000" = 5 USDT. */
    amount: string;
}
