// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         paymentId: "paymentId"
 *     }
 */
export interface GetV1PaymentsPaymentIdRequest {
    /** Payment ID */
    paymentId: string;
}
