// This file was auto-generated by Fern from our API Definition.

import type * as SuwardSDK from "../../../../index.js";

/**
 * @example
 *     {}
 */
export interface GetV1PaymentsRequest {
    /** Sort order (asc/desc) */
    order?: SuwardSDK.GetV1PaymentsRequestOrder;
    /** Limit (default 20, max 100) */
    limit?: number;
    /** Last ID for pagination */
    lastId?: string;
}
