// This file was auto-generated by Fern from our API Definition.

import type * as SuwardSDK from "../../../../index.js";

/**
 * @example
 *     {
 *         paymentId: "paymentId"
 *     }
 */
export interface GetV1PaymentsPaymentIdTransactionsRequest {
    /** Payment ID */
    paymentId: string;
    /** Sort order by id: asc = ascending, anything else = descending */
    order?: SuwardSDK.GetV1PaymentsPaymentIdTransactionsRequestOrder;
    /** Page size (default 20, max 100) */
    limit?: number;
    /** Pagination cursor: last id from the previous page */
    lastId?: string;
}
