// This file was auto-generated by Fern from our API Definition.

import * as core from "../core/index.js";

const TIMESTAMP_TOLERANCE_SECONDS = 300;
const SIGNATURE_PREFIX = "ed25519=";

/**
 * Verify an asymmetric webhook signature.
 *
 * Extract the signature from the "X-Suward-Signature" header and pass it as the signatureHeader parameter.
 * Extract the timestamp from the "X-Suward-Timestamp" header and pass it as the timestampHeader parameter.
 */
export class WebhooksHelper {
    public static async verifySignature(
        requestBody: string,
        signatureHeader: string,
        publicKey: string,
        timestampHeader: string,
    ): Promise<boolean> {
        if (requestBody == null || signatureHeader == null || publicKey == null) {
            throw new Error("Missing required parameters for webhook signature verification");
        }

        if (timestampHeader == null || timestampHeader === "") {
            throw new Error("Missing timestamp header 'X-Suward-Timestamp' for webhook signature verification");
        }

        const timestampValue = parseInt(timestampHeader, 10);
        if (Number.isNaN(timestampValue)) {
            throw new Error("Invalid timestamp format: expected unix milliseconds");
        }
        const timestampMs = timestampValue;

        if (Math.abs(Date.now() - timestampMs) > TIMESTAMP_TOLERANCE_SECONDS * 1000) {
            return false;
        }

        const sig = signatureHeader.startsWith(SIGNATURE_PREFIX)
            ? signatureHeader.slice(SIGNATURE_PREFIX.length)
            : signatureHeader;

        const payload = requestBody;

        return await core.verifyAsymmetricSignature({
            payload: payload,
            signature: sig,
            publicKey: publicKey,
            algorithm: "ED25519",
            encoding: "hex",
        });
    }
}
