// This file was auto-generated by Fern from our API Definition.

import * as SuwardSDK from "../../src/api/index";
import { SuwardSDKClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("PaymentsClient", () => {
    test("listPayments (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new SuwardSDKClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            hasMore: true,
            items: [
                {
                    acceptedAt: 1,
                    activatedAt: 1,
                    activationFlowSeconds: 1,
                    address: "address",
                    amount: "amount",
                    amountConfirmed: "amountConfirmed",
                    amountReceived: "amountReceived",
                    asset: "USDT_ETHEREUM",
                    createdAt: 1,
                    expiresAt: 1,
                    externalId: "externalId",
                    fee: "fee",
                    id: "id",
                    isTest: true,
                    metadata: { key: "value" },
                    networkFee: "networkFee",
                    quotedPrice: "quotedPrice",
                    networkFeePayer: "absorbed",
                    serviceFeePayer: "absorbed",
                    paymentWindowSeconds: 1,
                    projectId: "projectId",
                    status: "pending",
                    subStatus: "created",
                    transactions: [{}],
                    underpaymentTolerance: "underpaymentTolerance",
                    updatedAt: 1,
                    webhookUrl: "webhookUrl",
                    paymentPageUrl: "paymentPageUrl",
                },
            ],
            lastId: "lastId",
        };

        server.mockEndpoint().get("/v1/payments").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.payments.listPayments();
        expect(response).toEqual(rawResponseBody);
    });

    test("listPayments (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new SuwardSDKClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server.mockEndpoint().get("/v1/payments").respondWith().statusCode(400).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.payments.listPayments();
        }).rejects.toThrow(SuwardSDK.BadRequestError);
    });

    test("listPayments (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new SuwardSDKClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server.mockEndpoint().get("/v1/payments").respondWith().statusCode(401).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.payments.listPayments();
        }).rejects.toThrow(SuwardSDK.UnauthorizedError);
    });

    test("listPayments (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new SuwardSDKClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server.mockEndpoint().get("/v1/payments").respondWith().statusCode(500).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.payments.listPayments();
        }).rejects.toThrow(SuwardSDK.InternalServerError);
    });

    test("createPayment (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new SuwardSDKClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {
            acceptedAt: 1,
            activatedAt: 1,
            activationFlowSeconds: 1,
            address: "address",
            amount: "amount",
            amountConfirmed: "amountConfirmed",
            amountReceived: "amountReceived",
            asset: "USDT_ETHEREUM",
            createdAt: 1,
            expiresAt: 1,
            externalId: "externalId",
            fee: "fee",
            id: "id",
            isTest: true,
            metadata: { key: "value" },
            networkFee: "networkFee",
            quotedPrice: "quotedPrice",
            networkFeePayer: "absorbed",
            serviceFeePayer: "absorbed",
            paymentWindowSeconds: 1,
            projectId: "projectId",
            redirectConfig: { data: "data", params: ["id"], url: "url" },
            status: "pending",
            subStatus: "created",
            transactions: [{ acceptedAt: 1, amount: "amount", detectedAt: 1, txHash: "txHash" }],
            underpaymentTolerance: "underpaymentTolerance",
            updatedAt: 1,
            webhookUrl: "webhookUrl",
            paymentPageUrl: "paymentPageUrl",
        };

        server
            .mockEndpoint()
            .post("/v1/payments")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.payments.createPayment();
        expect(response).toEqual(rawResponseBody);
    });

    test("createPayment (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new SuwardSDKClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/v1/payments")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.payments.createPayment();
        }).rejects.toThrow(SuwardSDK.BadRequestError);
    });

    test("createPayment (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new SuwardSDKClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/v1/payments")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.payments.createPayment();
        }).rejects.toThrow(SuwardSDK.UnauthorizedError);
    });

    test("createPayment (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new SuwardSDKClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/v1/payments")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.payments.createPayment();
        }).rejects.toThrow(SuwardSDK.InternalServerError);
    });

    test("getPayment (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new SuwardSDKClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            acceptedAt: 1,
            activatedAt: 1,
            activationFlowSeconds: 1,
            address: "address",
            amount: "amount",
            amountConfirmed: "amountConfirmed",
            amountReceived: "amountReceived",
            asset: "USDT_ETHEREUM",
            createdAt: 1,
            expiresAt: 1,
            externalId: "externalId",
            fee: "fee",
            id: "id",
            isTest: true,
            metadata: { key: "value" },
            networkFee: "networkFee",
            quotedPrice: "quotedPrice",
            networkFeePayer: "absorbed",
            serviceFeePayer: "absorbed",
            paymentWindowSeconds: 1,
            projectId: "projectId",
            redirectConfig: { data: "data", params: ["id"], url: "url" },
            status: "pending",
            subStatus: "created",
            transactions: [{ acceptedAt: 1, amount: "amount", detectedAt: 1, txHash: "txHash" }],
            underpaymentTolerance: "underpaymentTolerance",
            updatedAt: 1,
            webhookUrl: "webhookUrl",
            paymentPageUrl: "paymentPageUrl",
        };

        server
            .mockEndpoint()
            .get("/v1/payments/paymentId")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.payments.getPayment({
            paymentId: "paymentId",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("getPayment (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new SuwardSDKClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/v1/payments/paymentId")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.payments.getPayment({
                paymentId: "paymentId",
            });
        }).rejects.toThrow(SuwardSDK.InternalServerError);
    });

    test("activatePayment (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new SuwardSDKClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            activatedAt: 1,
            activationFlowSeconds: 1,
            address: "address",
            amount: "amount",
            amountReceived: "amountReceived",
            asset: "USDT_ETHEREUM",
            createdAt: 1,
            expiresAt: 1,
            id: "id",
            paymentWindowSeconds: 1,
            redirect: { query: { key: "value" }, url: "url" },
            status: "pending",
            subStatus: "created",
            underpaymentTolerance: "underpaymentTolerance",
            updatedAt: 1,
            paymentPageUrl: "paymentPageUrl",
        };

        server
            .mockEndpoint()
            .post("/v1/payments/paymentId/activate")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.payments.activatePayment({
            paymentId: "paymentId",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("activatePayment (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new SuwardSDKClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/v1/payments/paymentId/activate")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.payments.activatePayment({
                paymentId: "paymentId",
            });
        }).rejects.toThrow(SuwardSDK.InternalServerError);
    });

    test("cancelPayment (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new SuwardSDKClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            acceptedAt: 1,
            activatedAt: 1,
            activationFlowSeconds: 1,
            address: "address",
            amount: "amount",
            amountConfirmed: "amountConfirmed",
            amountReceived: "amountReceived",
            asset: "USDT_ETHEREUM",
            createdAt: 1,
            expiresAt: 1,
            externalId: "externalId",
            fee: "fee",
            id: "id",
            isTest: true,
            metadata: { key: "value" },
            networkFee: "networkFee",
            quotedPrice: "quotedPrice",
            networkFeePayer: "absorbed",
            serviceFeePayer: "absorbed",
            paymentWindowSeconds: 1,
            projectId: "projectId",
            redirectConfig: { data: "data", params: ["id"], url: "url" },
            status: "pending",
            subStatus: "created",
            transactions: [{ acceptedAt: 1, amount: "amount", detectedAt: 1, txHash: "txHash" }],
            underpaymentTolerance: "underpaymentTolerance",
            updatedAt: 1,
            webhookUrl: "webhookUrl",
            paymentPageUrl: "paymentPageUrl",
        };

        server
            .mockEndpoint()
            .post("/v1/payments/paymentId/cancel")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.payments.cancelPayment({
            paymentId: "paymentId",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("cancelPayment (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new SuwardSDKClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/v1/payments/paymentId/cancel")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.payments.cancelPayment({
                paymentId: "paymentId",
            });
        }).rejects.toThrow(SuwardSDK.UnauthorizedError);
    });

    test("cancelPayment (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new SuwardSDKClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/v1/payments/paymentId/cancel")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.payments.cancelPayment({
                paymentId: "paymentId",
            });
        }).rejects.toThrow(SuwardSDK.InternalServerError);
    });

    test("simulatePayment (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new SuwardSDKClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {
            acceptedAt: 1,
            activatedAt: 1,
            activationFlowSeconds: 1,
            address: "address",
            amount: "amount",
            amountConfirmed: "amountConfirmed",
            amountReceived: "amountReceived",
            asset: "USDT_ETHEREUM",
            createdAt: 1,
            expiresAt: 1,
            externalId: "externalId",
            fee: "fee",
            id: "id",
            isTest: true,
            metadata: { key: "value" },
            networkFee: "networkFee",
            quotedPrice: "quotedPrice",
            networkFeePayer: "absorbed",
            serviceFeePayer: "absorbed",
            paymentWindowSeconds: 1,
            projectId: "projectId",
            redirectConfig: { data: "data", params: ["id"], url: "url" },
            status: "pending",
            subStatus: "created",
            transactions: [{ acceptedAt: 1, amount: "amount", detectedAt: 1, txHash: "txHash" }],
            underpaymentTolerance: "underpaymentTolerance",
            updatedAt: 1,
            webhookUrl: "webhookUrl",
            paymentPageUrl: "paymentPageUrl",
        };

        server
            .mockEndpoint()
            .post("/v1/payments/paymentId/simulate")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.payments.simulatePayment({
            paymentId: "paymentId",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("simulatePayment (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new SuwardSDKClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/v1/payments/paymentId/simulate")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.payments.simulatePayment({
                paymentId: "paymentId",
            });
        }).rejects.toThrow(SuwardSDK.BadRequestError);
    });

    test("simulatePayment (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new SuwardSDKClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/v1/payments/paymentId/simulate")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.payments.simulatePayment({
                paymentId: "paymentId",
            });
        }).rejects.toThrow(SuwardSDK.UnauthorizedError);
    });

    test("simulatePayment (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new SuwardSDKClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/v1/payments/paymentId/simulate")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.payments.simulatePayment({
                paymentId: "paymentId",
            });
        }).rejects.toThrow(SuwardSDK.InternalServerError);
    });

    test("quotePaymentFees (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new SuwardSDKClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { asset: "USDT_ETHEREUM", amount: "amount" };
        const rawResponseBody = {
            asset: "USDT_ETHEREUM",
            amount: "amount",
            fee: "fee",
            networkFee: "networkFee",
            netAmount: "netAmount",
            gross: "gross",
            quotedPrice: "quotedPrice",
        };

        server
            .mockEndpoint()
            .post("/v1/payments/quote")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.payments.quotePaymentFees({
            asset: "USDT_ETHEREUM",
            amount: "amount",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("quotePaymentFees (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new SuwardSDKClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { asset: "USDT_ETHEREUM", amount: "amount" };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/v1/payments/quote")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.payments.quotePaymentFees({
                asset: "USDT_ETHEREUM",
                amount: "amount",
            });
        }).rejects.toThrow(SuwardSDK.BadRequestError);
    });

    test("quotePaymentFees (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new SuwardSDKClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { asset: "USDT_ETHEREUM", amount: "amount" };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/v1/payments/quote")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.payments.quotePaymentFees({
                asset: "USDT_ETHEREUM",
                amount: "amount",
            });
        }).rejects.toThrow(SuwardSDK.UnauthorizedError);
    });

    test("quotePaymentFees (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new SuwardSDKClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { asset: "USDT_ETHEREUM", amount: "amount" };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/v1/payments/quote")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.payments.quotePaymentFees({
                asset: "USDT_ETHEREUM",
                amount: "amount",
            });
        }).rejects.toThrow(SuwardSDK.InternalServerError);
    });
});
