// This file was auto-generated by Fern from our API Definition.

import * as SuwardSDK from "../../src/api/index";
import { SuwardSDKClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("StaticWalletsClient", () => {
    test("listStaticWallets (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new SuwardSDKClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            hasMore: true,
            items: [
                {
                    address: "address",
                    allowedAssets: ["USDT_ETHEREUM"],
                    createdAt: 1,
                    externalId: "externalId",
                    id: "id",
                    metadata: { key: "value" },
                    projectId: "projectId",
                    updatedAt: 1,
                    webhookUrl: "webhookUrl",
                },
            ],
        };

        server.mockEndpoint().get("/v1/static-wallets").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.staticWallets.listStaticWallets();
        expect(response).toEqual(rawResponseBody);
    });

    test("listStaticWallets (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new SuwardSDKClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server.mockEndpoint().get("/v1/static-wallets").respondWith().statusCode(401).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.staticWallets.listStaticWallets();
        }).rejects.toThrow(SuwardSDK.UnauthorizedError);
    });

    test("createStaticWallet (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new SuwardSDKClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {
            address: "address",
            allowedAssets: ["USDT_ETHEREUM"],
            createdAt: 1,
            externalId: "externalId",
            id: "id",
            metadata: { key: "value" },
            projectId: "projectId",
            updatedAt: 1,
            webhookUrl: "webhookUrl",
        };

        server
            .mockEndpoint()
            .post("/v1/static-wallets")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.staticWallets.createStaticWallet();
        expect(response).toEqual(rawResponseBody);
    });

    test("createStaticWallet (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new SuwardSDKClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/v1/static-wallets")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.staticWallets.createStaticWallet();
        }).rejects.toThrow(SuwardSDK.BadRequestError);
    });

    test("createStaticWallet (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new SuwardSDKClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/v1/static-wallets")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.staticWallets.createStaticWallet();
        }).rejects.toThrow(SuwardSDK.UnauthorizedError);
    });

    test("getStaticWallet (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new SuwardSDKClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            address: "address",
            allowedAssets: ["USDT_ETHEREUM"],
            createdAt: 1,
            externalId: "externalId",
            id: "id",
            metadata: { key: "value" },
            projectId: "projectId",
            updatedAt: 1,
            webhookUrl: "webhookUrl",
        };

        server
            .mockEndpoint()
            .get("/v1/static-wallets/staticWalletId")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.staticWallets.getStaticWallet({
            staticWalletId: "staticWalletId",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("getStaticWallet (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new SuwardSDKClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/v1/static-wallets/staticWalletId")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.staticWallets.getStaticWallet({
                staticWalletId: "staticWalletId",
            });
        }).rejects.toThrow(SuwardSDK.NotFoundError);
    });

    test("deleteStaticWallet (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new SuwardSDKClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: true };

        server
            .mockEndpoint()
            .delete("/v1/static-wallets/staticWalletId")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.staticWallets.deleteStaticWallet({
            staticWalletId: "staticWalletId",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("deleteStaticWallet (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new SuwardSDKClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .delete("/v1/static-wallets/staticWalletId")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.staticWallets.deleteStaticWallet({
                staticWalletId: "staticWalletId",
            });
        }).rejects.toThrow(SuwardSDK.NotFoundError);
    });

    test("updateStaticWallet (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new SuwardSDKClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {
            address: "address",
            allowedAssets: ["USDT_ETHEREUM"],
            createdAt: 1,
            externalId: "externalId",
            id: "id",
            metadata: { key: "value" },
            projectId: "projectId",
            updatedAt: 1,
            webhookUrl: "webhookUrl",
        };

        server
            .mockEndpoint()
            .patch("/v1/static-wallets/staticWalletId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.staticWallets.updateStaticWallet({
            staticWalletId: "staticWalletId",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("updateStaticWallet (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new SuwardSDKClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .patch("/v1/static-wallets/staticWalletId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.staticWallets.updateStaticWallet({
                staticWalletId: "staticWalletId",
            });
        }).rejects.toThrow(SuwardSDK.BadRequestError);
    });

    test("listStaticWalletDeposits (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new SuwardSDKClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            hasMore: true,
            items: [
                {
                    acceptedAt: 1,
                    address: "address",
                    amount: "amount",
                    asset: "USDT_ETHEREUM",
                    confirmedAt: 1,
                    createdAt: 1,
                    detectedAt: 1,
                    externalId: "externalId",
                    fee: "fee",
                    id: "id",
                    invalidatedAt: 1,
                    netAmount: "netAmount",
                    networkFee: "networkFee",
                    projectId: "projectId",
                    staticWalletId: "staticWalletId",
                    status: "detected",
                    transferIndex: "transferIndex",
                    txHash: "txHash",
                    updatedAt: 1,
                },
            ],
        };

        server
            .mockEndpoint()
            .get("/v1/static-wallets/staticWalletId/deposits")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.staticWallets.listStaticWalletDeposits({
            staticWalletId: "staticWalletId",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("listStaticWalletDeposits (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new SuwardSDKClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/v1/static-wallets/staticWalletId/deposits")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.staticWallets.listStaticWalletDeposits({
                staticWalletId: "staticWalletId",
            });
        }).rejects.toThrow(SuwardSDK.NotFoundError);
    });

    test("getStaticWalletDeposit (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new SuwardSDKClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            acceptedAt: 1,
            address: "address",
            amount: "amount",
            asset: "USDT_ETHEREUM",
            confirmedAt: 1,
            createdAt: 1,
            detectedAt: 1,
            externalId: "externalId",
            fee: "fee",
            id: "id",
            invalidatedAt: 1,
            netAmount: "netAmount",
            networkFee: "networkFee",
            projectId: "projectId",
            staticWalletId: "staticWalletId",
            status: "detected",
            transferIndex: "transferIndex",
            txHash: "txHash",
            updatedAt: 1,
        };

        server
            .mockEndpoint()
            .get("/v1/static-wallets/staticWalletId/deposits/depositId")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.staticWallets.getStaticWalletDeposit({
            staticWalletId: "staticWalletId",
            depositId: "depositId",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("getStaticWalletDeposit (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new SuwardSDKClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/v1/static-wallets/staticWalletId/deposits/depositId")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.staticWallets.getStaticWalletDeposit({
                staticWalletId: "staticWalletId",
                depositId: "depositId",
            });
        }).rejects.toThrow(SuwardSDK.UnauthorizedError);
    });

    test("getStaticWalletDeposit (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new SuwardSDKClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/v1/static-wallets/staticWalletId/deposits/depositId")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.staticWallets.getStaticWalletDeposit({
                staticWalletId: "staticWalletId",
                depositId: "depositId",
            });
        }).rejects.toThrow(SuwardSDK.NotFoundError);
    });

    test("simulateStaticWalletDeposit (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new SuwardSDKClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {
            acceptedAt: 1,
            address: "address",
            amount: "amount",
            asset: "USDT_ETHEREUM",
            confirmedAt: 1,
            createdAt: 1,
            detectedAt: 1,
            externalId: "externalId",
            fee: "fee",
            id: "id",
            invalidatedAt: 1,
            netAmount: "netAmount",
            networkFee: "networkFee",
            projectId: "projectId",
            staticWalletId: "staticWalletId",
            status: "detected",
            transferIndex: "transferIndex",
            txHash: "txHash",
            updatedAt: 1,
        };

        server
            .mockEndpoint()
            .post("/v1/static-wallets/staticWalletId/simulate")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.staticWallets.simulateStaticWalletDeposit({
            staticWalletId: "staticWalletId",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("simulateStaticWalletDeposit (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new SuwardSDKClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/v1/static-wallets/staticWalletId/simulate")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.staticWallets.simulateStaticWalletDeposit({
                staticWalletId: "staticWalletId",
            });
        }).rejects.toThrow(SuwardSDK.BadRequestError);
    });

    test("simulateStaticWalletDeposit (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new SuwardSDKClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/v1/static-wallets/staticWalletId/simulate")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.staticWallets.simulateStaticWalletDeposit({
                staticWalletId: "staticWalletId",
            });
        }).rejects.toThrow(SuwardSDK.NotFoundError);
    });
});
