// This file was auto-generated by Fern from our API Definition.

export const SuwardSDKEnvironment = {
    Default: "https://api.suward.com",
} as const;

export type SuwardSDKEnvironment = typeof SuwardSDKEnvironment.Default;
