// This file was auto-generated by Fern from our API Definition.

export const GetV1PaymentsRequestOrder = {
    Asc: "asc",
    Desc: "desc",
} as const;
export type GetV1PaymentsRequestOrder = (typeof GetV1PaymentsRequestOrder)[keyof typeof GetV1PaymentsRequestOrder];
