// This file was auto-generated by Fern from our API Definition.

export const GetV1PaymentsPaymentIdTransactionsRequestOrder = {
    Asc: "asc",
    Desc: "desc",
} as const;
export type GetV1PaymentsPaymentIdTransactionsRequestOrder =
    (typeof GetV1PaymentsPaymentIdTransactionsRequestOrder)[keyof typeof GetV1PaymentsPaymentIdTransactionsRequestOrder];
